AWSTemplateFormatVersion: 2010-09-09
Parameters:
  InstanceType:
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro
      - t2.small
    Description: Enter t2.micro, t2.small. Default is t2.micro.
  AMI:
    Type: String
    Default: ami-010aff33ed5991201
    Description: The Windows AMI to use.
  AZ:
   Type: String
   Default: ap-south-1b
   Description: AZ for instance
  Key:
    Description: The key used to access the instance.
    Type: AWS::EC2::KeyPair::KeyName
Resources:
  Webserver:
    Type: 'AWS::EC2::Instance'
    Properties:
      ImageId:
        Ref: AMI
      InstanceType:
        Ref: InstanceType
      KeyName: 
        Ref : Key
      AvailabilityZone:
         Ref: AZ
      SecurityGroupIds:
         Ref: WebServerSG
  WebServerSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: "WebServerSG"
      GroupDescription: "WebServerSG"
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: '80'
          ToPort: '80'
          CidrIp: 0.0.0.0/0  
      SecurityGroupEgress:
        - IpProtocol: tcp
          CidrIp: 0.0.0.0/0


  